### ISSUE TITLE
Unexpected behaviour when mediator target has a property/field named "length"

### ISSUE THREAD

**Issue by bullno1** [somajs/somajs#13]
Due to this part, any mediator target with a field named `length` (and not necessarily an array) will be treated differently: https://github.com/somajs/somajs/blob/master/src/core.js#L129.

This is especially problematic for a `<form>` element since it seems to be the only element that has a `length` field: https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/length. Though one can argue that it is indeed array-like, this kind of behaviour is quite unexptected.

I propose that mediator should follow only a single interface out of one of the following:

1. Only one target. If an array is passed, _the array itself_ is the target.
2. Only an array, for a single target, use a literal array, i.e: `mediators.create(Mediator, [target])`
3. Use varargs: `mediators.create(Mediator, target1, target2, target3)`

**Comment by soundstep** [comment]
Hi,

This is a good point.
The ```length``` check was originally made to handle directly ```querySelectorAll```:

```
mediators.create(Mediator, document.querySelectorAll('.a_css_class'));
```

As the result of a ```querySelectorAll``` is not a proper array, it can't be tested the usual way.
I'll have a look to see what can be done.

**Comment by soundstep** [comment]
Note for myself:

Implement a check to tests array and node list:

```
Object.prototype.toString.call(document.querySelectorAll('p')) === '[object NodeList]'
Object.prototype.toString.call([]) === '[object Array]'
```
